// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC74qGnEwtq59JdtPmGu3f0k1ikWK4NmdI',
    appId: '1:507110796691:web:b5bee98ebee04d3afc8c66',
    messagingSenderId: '507110796691',
    projectId: 'flutter-gallery-app-ed273',
    authDomain: 'flutter-gallery-app-ed273.firebaseapp.com',
    storageBucket: 'flutter-gallery-app-ed273.appspot.com',
    measurementId: 'G-NRPQST0BXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLj4VCLIzpZ6tw0FpJzkaJeGxg05hIIZw',
    appId: '1:507110796691:android:3300e51059e6bb1cfc8c66',
    messagingSenderId: '507110796691',
    projectId: 'flutter-gallery-app-ed273',
    storageBucket: 'flutter-gallery-app-ed273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMlIQ2HOBTJ_LW5lGtqtpHV_-eUiPqki8',
    appId: '1:507110796691:ios:28dbbc6ceab47920fc8c66',
    messagingSenderId: '507110796691',
    projectId: 'flutter-gallery-app-ed273',
    storageBucket: 'flutter-gallery-app-ed273.appspot.com',
    iosBundleId: 'com.example.flutterGalleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMlIQ2HOBTJ_LW5lGtqtpHV_-eUiPqki8',
    appId: '1:507110796691:ios:2095bf0abbc9ce21fc8c66',
    messagingSenderId: '507110796691',
    projectId: 'flutter-gallery-app-ed273',
    storageBucket: 'flutter-gallery-app-ed273.appspot.com',
    iosBundleId: 'com.example.flutterGalleryApp.RunnerTests',
  );
}
